language: cpp
cache: apt
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libtool autotools-dev autoconf libssl-dev pkg-config ccache lcov python-yaml python-requests
  - sudo apt-get install libboost1.48-dev libboost-chrono1.48-dev libboost-filesystem1.48-dev libboost-program-options1.48-dev libboost-system1.48-dev libboost-test1.48-dev libboost-thread1.48-dev
  - sudo apt-get install libdb++-dev
  - sudo apt-get install libqt4-dev 
  - sudo apt-get install  libprotobuf-dev protobuf-compiler
  - sudo pip install cpp-coveralls
  - mkdir $HOME/.ccache
  - export CCACHE_DIR=$HOME/.ccache
  - ccache -M 1G
script:
  - ./autogen.sh

  - CFLAGS="-O1" CXXFLAGS="-O1" ./configure --enable-lcov --disable-ccache
  - make -j 2
  - make check
after_success:
  - coveralls --gcov /usr/bin/gcov -x cpp --verbose | tail -n2000
  